#pour installer mongoBD et après avoir l'interface
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    #permet d'attendre que mongo se lance avant de lancer express
    depend_on:
      - mongo